name: Node Eats CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: nodeeats

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'yarn'
          cache-dependency-path: nodeeats/yarn.lock

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Check TypeScript
        run: yarn tsc --noEmit

      - name: Run ESLint
        run: yarn lint

      - name: Run Prettier
        run: yarn format

      - name: Run tests
        run: yarn test

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          flags: unit-tests
          name: coverage-nodeeats
          files: nodeeats/coverage/lcov.info
          verbose: true
          token: ${{ secrets.CODECOV_TOKEN }}
